M48
; DRILL file {KiCad (6.0.10-0)} date Friday, February 17, 2023 at 03:38:27 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-17T15:38:27-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10-0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0598
%
G90
G05
T1
X5.2Y-3.4
X5.2Y-3.5
X5.2Y-3.7
X5.4Y-3.5
X5.5Y-3.3
X5.5Y-3.4
X5.6Y-3.6
X5.6Y-3.8
T2
X5.3Y-3.0
X5.5Y-3.0
T0
M30
